### PR TITLE
Replace IOData methods to_file and from_file by functions

### PR DESCRIPTION
**Pull request by tovrstra**
New functions are ``load_one`` and ``dump_one``. This is the first step described in #7. I'm trying to get this done soon to make life easier for @evohringer and @fwmeng88.

### CODE REVIEW

**Comment by evohringer** [comment]
I think the changes are reasonable, but cannot really aprove it.

**Comment by tovrstra** [comment]
@evohringer Do you mean that you have no approve functionality on the github website? If needed, I can try to fix some settings.

**Comment by tovrstra** [comment]
`dump_one1 has become a function (indented back four spaces compared to old code), so it does not have the `self` argument anymore. Instead it needs something to know which information to write to a file, which has now become the first `iodata` argument of the function. It is very similar to the old method, but no longer tied closely to the `IOData` class.

**Comment by evohringer** [comment]
> `dump_one` has become a function (indented back four spaces compared to old code), so it does not have the `self` argument anymore. Instead it needs something to know which information to write to a file, which has now become the first `iodata` argument of the function. It is very similar to the old method, but no longer tied closely to the `IOData` class.

Thanks. I just saw the indentation.

**Pull request merged**
