### PR TITLE
Add edit page button and link to GitHub in docs

### PR DESCRIPTION
**Pull request by tovrstra**
One of the minor items in #204.

Based on:
- https://pradyunsg.me/furo/customisation/top-of-page-buttons/
- https://pradyunsg.me/furo/customisation/footer/

I will YOLO-merge this on Friday, June 21, unless reviewed earlier

## Summary by Sourcery

This pull request updates the documentation configuration to include a button for editing pages and a link to the GitHub repository, enhancing the user experience by providing easy access to the source code and the ability to contribute.

* **Documentation**:
    - Added a button to edit pages and a link to the GitHub repository in the documentation.

### CODE REVIEW

**Comment by tovrstra** [comment]
Tests fail due to #340

**Review by PaulWAyers — APPROVED** [review]
Thanks Toon.

**Comment by tovrstra** [comment]
Just to play safe, I'll merge main into this PR and rerun tests (with the NumPy 2 fix).

**Comment by tovrstra** [comment]
Thanks for reviewing. merging...

**Pull request merged**
