### PR TITLE
Add dump_one() function for WFX

### PR DESCRIPTION
**Pull request by fwmeng88**
With the help of Leila, we have added the functionality of `dump_one()` for WFX format.

- [x] Implementation `dump_one()` support for WFX 
- [x] Add tests for dump_one()
- [x] Fix pylinter errors: missing shite spaces, docstring formatting, identation 

Thanks for the nice contributions! @leila-pujal

### CODE REVIEW

**Comment by FarnazH** [comment]
@fwmeng88 thanks for making a PR. I believe, @leila-pujal is still working on the code to have it supports `obasis` which is not only primitives so that one can load FCHk and dump WFX.

**Comment by fwmeng88** [comment]
> @fwmeng88 thanks for making a PR. I believe, @leila-pujal is still working on the code to have it supports `obasis` which is not only primitives so that one can load FCHk and dump WFX.

Thank you, Farnaz. This PR will help other in the iodata group knows some updates on WFX such we are more ready for this Friday's meeting.

**Comment by leila-pujal** [comment]
I tried to load several wfx and wfn with AIMALL Version 14.06.21 Professional and I didn’t find any issue or error in the output. I load wfx/wfn for water sto-3g converted from wfx, wfn, molden and fchk and for water cc-pvtz converted from fchk. In all of them number of primitives were correct, QTAIM critical point analysis detected 3 NACPs and 2 BCPs  and net charge for each atom is the same as the one obtained with the original wfx/wfn. Let me know if you want me to check anything else you think is important.

**Comment by FarnazH** [comment]
Thanks a lot for your detailed checks @leila-pujal. I agree @tovrstra, we will refactor basis de-contraction, and factor it out of WFX/WFN `dump_one` in a later PR.

**Pull request merged**
