### PR TITLE
(WIP) Add JSON input/output functionality

### PR DESCRIPTION
**Pull request by wilhadams**
Add `load_one` and `dump_one` functions for the QCSchema JSON filetype.

As a result of inconsistent implementation in the QCSchema repo, QCElemental, and the Basis Set Exchange, doing this will require building an updated specification for the QCSchema. I've tried to keep this as backwards-compatible as possible, with some exceptions: QCElemental, for example, has a basis specification definition that differs from both other sources, however, that basis spec was never fully implemented in QCElemental, so there's no reason to be held hostage to that definition. 

There are currently 76 test files in the `json_tests_qcrecords` directory and 21 in the `json_tests_qcschemadev` that are being used to test most of the implementation, however, at this point there isn't a "perfect example" for every field in (any variant of) the schema. I will pick good examples from these batches and generate valid JSON files for cases without a test case. 

This PR is still a bit of a mess, I'll have it cleaned up soon.

### CODE REVIEW

**Comment by wilhadams** [comment]
QCSchema uses CCA conventions, so this is relevant to #79

**Comment by PaulWAyers** [comment]
Does this mean that Issue #79 will be resolved after this pull request is merged?

**Comment by wilhadams** [comment]
@PaulWAyers that was vague, sorry. Yes, I'll make sure that this PR closes #79

**Comment by wilhadams** [comment]
Different parts of the QCSchema are at different levels of maturity right now, in addition to different levels of availability for examples, ranging from none to not many. I'm going to close this PR and break it into several smaller PRs to get the better-tested stuff out and start working on generating tests for the other parts.

**Pull request closed without merging**
