### PR TITLE
Add AppVeyor continuous integration

### PR DESCRIPTION
**Pull request by FarnazH**
There is a problem with `iodata/molden.py` on Windows due to `file.seek()` and `file.tell()` methods. This is because a different newline character is used on Windows, so seek does not take you back to the exact same place (beginning of the previously read line).

### CODE REVIEW

**Comment by FarnazH** [comment]
P.S. This is a problem with only Python 2.7 on Windows apparently because Python 3.5 and 3.6 changed the way `file.seek()` and `file.tell()` work.

**Comment by tovrstra** [comment]
We should probably rewrite the code not to use seek and tell. That is a rather fragile technique anyway.

**Comment by tovrstra** [comment]
P.S. I've updated the webhook to point to Roberto's account on AppVeyor.

**Comment by tovrstra** [comment]
This is the badge for appveyor:

```[Build status](https://ci.appveyor.com/project/theochem-ci-bot/iodata/branch/master)```

When you push this a new commit (e.g. with the badge) it should start testing on appveyor as well.

**Comment by tovrstra** [comment]
We'll fix the seek and tell later. Merging.

**Pull request merged**
