### PR TITLE
Fix Failure in Parsing Q-Chem Fchk

### PR DESCRIPTION
**Pull request by FarnazH**
The FCHK files generated by Q-Chem 5.2 & 5.3 does not contain "Total Energy", so parsing them with IOData fails. The code is changed to return `None` for `energy`, if "Total Energy" is not present in FCHK file; as a result, `energy` becomes an ifpresent value. 

Here are examples of FCHK generated by Q-Chem 5.2 & 5.3:
[Water_qchem5.2.fchk.tar.gz](https://github.com/theochem/iodata/files/5144896/Water_qchem5.2.fchk.tar.gz)
[Water_qchem5.3.fchk.tar.gz](https://github.com/theochem/iodata/files/5144897/Water_qchem5.3.fchk.tar.gz)

I can generate any test file required, so please feel free to let me know what you think.

### CODE REVIEW

**Comment by tovrstra** [comment]
Looks good, I'd suggest to add a small (STO-3G water) fchk file to the tests to make sure it keeps working in future.

**Comment by FarnazH** [comment]
Sure, I will do that @tovrstra. If we are adding a Q-Chem FCHK test, does it make sense to include higher order angular momentum too, or FCHK files are robust across various softwares? I am asking because I am generating some Q-Chem Molden files for testing like Zn with pure/Cartesian cc-pvqz basis (following the existing examples).

**Comment by tovrstra** [comment]
@FarnazH That's a good point. You only know for sure if it works when it is tested.

**Review by evohringer — DISMISSED** [review]
Looks fine!

**Comment by evohringer** [comment]
One additional comment: The missing energy field also happens in molden files if I remember correctly. It might be an issue when using e.g. chemtools.

**Comment by FarnazH** [comment]
I will add a test fchk file from Q-Chem soon.
I agree @evohringer, we need to make sure proper error is raised if a user tries to use such files for computing certain descriptors with chemtools.

**Comment by tovrstra** [comment]
@FarnazH It would be nice to pick this one up again. Could you generate a smaller FCHK file with Q-Chem? The files you showed are relatively large. Thanks.

**Comment by FarnazH** [comment]
@tovrstra I used a small calculation, but feel free to let me know if any other test files are needed. I can easily generate them (I will be making a PR with a Q-Chem MOLDEN file soon).

**Review by tovrstra — APPROVED** [review]
Looks very good! Thanks.

**Pull request merged**
