### PR TITLE
Add gaussinput loader #228

### PR DESCRIPTION
**Pull request by tczorro**
1. Add load_one function in gaussianinput.py
2. Add tests for check load_one functionality for both
   .com and .gjf files with different Link 0 section

### CODE REVIEW

**Comment by tovrstra** [comment]
@tczorro Thanks for the PR. Overall it looks good. My only concern is that Gaussian input files tend to vary a lot in several aspects. A complete coverage of all those possibilities would go beyond the scope of this PR (or IOData in general), but the following variations are fairly common:
- multiple lines starting with `%` (link 0 commands), see e.g. https://www.cup.uni-muenchen.de/oc/zipse/teaching/computational-chemistry-2/topics/gaussian-input-files/
- No lines starting with `%`, see e.g. https://www.carc.unm.edu/~chem/gaussian/zmats.html
- Multiple lines starting with `#` (route section, see http://gaussian.com/input/)
- Multiple title lines (up to five, see http://gaussian.com/input/)
- Z-matrix for the geometry (which I would not bother parsing at this stage, just a friendly error message is fine)

Such cases in the unit tests would be ideal to make the implementation keeps working.

P.S. Could you rebase or merge master into your PR? CI is up and running again in the master branch.

**Comment by tczorro** [comment]
@tovrstra Thanks for the comments. I will update the PR with the new update to handle multiple-lines input in different cases.
Also I will add a warning if a Z-matrix is detected.

**Comment by tczorro** [comment]
Due to the indefinite format of route line(s) in gaussian, where key words are swappable and '/' omissible, the `lot` and `obasis_name` is not included in the final `data`. The contents parsed in the function will be `title`, `atnums`, `atcoords`.

**Comment by tovrstra** [comment]
Thanks! Going in ...

**Review by tovrstra — APPROVED** [review]

**Pull request merged**
