### PR TITLE
Extend saved atomic charges for fchk

### PR DESCRIPTION
**Pull request by leila-pujal**
Add new code to `fchk.py` to be able to extend the default saved set of charges to:
- MBS charges ( minimum basis set Mulliken population)
- Type 6 charges (Hirshfeld)
- Type 7 charges (cm5)

I checked the log file to assigned Type 6 and 7 but I couldn't find gaussian documentation to confirm it. I added a new test in test_fchk.py and a new fchk file to data to be able to test the new code.

### CODE REVIEW

**Review by FarnazH — CHANGES_REQUESTED** [review]
Thanks, @leila-pujal for extending the FCHK `load_one`. One thing just crossed my mind, we need to make sure the  `dump_one` also writes these charges; see https://github.com/theochem/iodata/blob/master/iodata/formats/fchk.py#L621

Can you please update `dump_one` too?

**Comment by leila-pujal** [comment]
Yes, you are right, I didn't remember about  `dump_one`. I will push the commits to account for that shortly

**Comment by leila-pujal** [comment]
I mapped again `hirshfeld` and `cm5` to `Type 6 Charges` and `Type 7 charges` when they are being dumped into a new fchk. Let me know if you want me to modify something else.

**Comment by tovrstra** [comment]
Looks good. I just have one minor request: could you add a test with `check_load_dump_consistency` for the new FCHK file? This will make sure the new dump code is covered by the tests.

(It is funny that the Gaussian developer decided to use the name Type 7 for CM5. I love it.)

**Comment by leila-pujal** [comment]
@tovrstra sorry for the late answer. I added the new test to compare the new and original fchk. I think now it looks like all the checks passed? Let me know if there's something missing.

**Comment by tovrstra** [comment]
It's perfect! Thank you, and no worries about the timing. We're all dealing with a lot of things. Time to merge...

**Review by tovrstra — APPROVED** [review]

**Pull request merged**
